name: Terraform
on:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 6.13.0

      - name: Terrafrom init
        run: |
          cd terraform
          terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform start
        run: terraform apply --auto-approve

      - name: Upload playbook.yml
        uses: actions/upload-artifact@v4
        with:
          name: inventory.ini
          path: ../ansible/inventory.ini

      # - name: Terraform destroy
      #   run: terraform destroy
